#5)	Afişaţi tabla înmulţirii cu numărul n
#Exemplu: pentru n=5, se va afişa pe verticală 1x5=5  2x5=10 3x5=15 4x5=20 5x5=25 6x5=30 7x5=35 8x5=40 9x5=45 10x5=50. 
#Din fişierul « numar.txt » se citeşte un număr, în fişierul « inmultire.txt » - se înscrie tabla înmulţirii cu acest număr.
with open('numar.txt','r') as j:
    a=j.readline()
b='1*'+int(a)+'='+(1*int(a))
c='2*'+int(a)+'='+(2*int(a))
d='3*'+int(a)+'='+(3*int(a))
e='4*'+int(a)+'='+(4*int(a))
f='5*'+int(a)+'='+(5*int(a))
g='6*'+int(a)+'='+(6*int(a))
h='7*'+int(a)+'='+(7*int(a))
i='8*'+int(a)+'='+(8*int(a))
j='9*'+int(a)+'='+(9*int(a))
k='10*'+int(a)+'='+(10*int(a))
with open('inmultire.txt','w') as l:
    l.write(str(b))
    l.write('\n')
    l.write(str(c))
    l.write('\n')
    l.write(str(d))
    l.write('\n')
    l.write(str(e))
    l.write('\n')
    l.write(str(f))
    l.write('\n')
    l.write(str(g))
    l.write('\n')
    l.write(str(h))
    l.write('\n')
    l.write(str(i))
    l.write('\n')
    l.write(str(j))
    l.write('\n')
    l.write(str(k))
